<?php
/**
 * Resolves a Country post to its bundled outline-map SVG URL.
 *
 * @package CountryWeek
 */

namespace CountryWeek\Utilities;

use CountryWeek\Services\Country_Manifest;
use WP_Post;

if (!defined('ABSPATH')) {
    exit;
}

/**
 * Static, stateless — no register() hook needed (see Date_Utility for
 * the same pattern). Maps live at assets/maps/countries/{manifest_key}.svg,
 * generated by scripts/build-country-maps.py from Natural Earth data;
 * see MAP-SOURCES.md for sourcing/licensing and per-country notes.
 */
class Map_Asset
{
    private const MAP_DIR = 'assets/maps/countries/';
    private const PLACEHOLDER_PATH = 'assets/maps/placeholder-country.svg';

    /**
     * Always returns a usable URL: the country's own map if one exists
     * on disk, otherwise the placeholder graphic.
     */
    public static function url_for(?WP_Post $country): string
    {
        $key = self::manifest_key_for($country);

        if ($key !== '') {
            $relative = self::MAP_DIR . $key . '.svg';

            if (file_exists(get_theme_file_path($relative))) {
                return get_theme_file_uri($relative);
            }
        }

        return get_theme_file_uri(self::PLACEHOLDER_PATH);
    }

    private static function manifest_key_for(?WP_Post $country): string
    {
        if (!$country instanceof WP_Post) {
            return '';
        }

        $key = get_post_meta($country->ID, Country_Manifest::meta_key(), true);

        if (!is_string($key) || $key === '') {
            return '';
        }

        // Defense in depth: manifest_key is already sanitize_key()'d on
        // save (see Country_Manifest::register_meta_field()), but this
        // value feeds directly into a filesystem path, so re-validate
        // rather than trust stored meta blindly.
        return preg_match('/^[a-z0-9-]+$/', $key) === 1 ? $key : '';
    }
}
